(ns elfeed-cljsrn.rn
  (:require [reagent.core :as r]))

(def ReactNative (js/require "react-native"))
(def app-registry (.-AppRegistry ReactNative))

(def navigation-header-raw (.-Header (.-NavigationExperimental ReactNative)))
(def navigation-header (r/adapt-react-class navigation-header-raw))
(def navigation-header-title (r/adapt-react-class (.-Title navigation-header-raw)))
(def navigation-card-stack (r/adapt-react-class (.-CardStack (.-NavigationExperimental ReactNative))))
(def text (r/adapt-react-class (.-Text ReactNative)))
(def text-input (r/adapt-react-class (.-TextInput ReactNative)))
(def view (r/adapt-react-class (.-View ReactNative)))
(def web-view (r/adapt-react-class (.-WebView ReactNative)))
(def image (r/adapt-react-class (.-Image ReactNative)))
(def list-view (r/adapt-react-class (.-ListView ReactNative)))
(def swipeable-list-view (r/adapt-react-class (.-SwipeableListView ReactNative)))
(def touchable-highlight (r/adapt-react-class (.-TouchableHighlight ReactNative)))
(def touchable-without-feedback (r/adapt-react-class (.-TouchableWithoutFeedback ReactNative)))
(def touchable (r/adapt-react-class (.-TouchableNativeFeedback ReactNative)))
(def touchable-opacity (r/adapt-react-class (.-TouchableOpacity ReactNative)))
(def drawer-layout (r/adapt-react-class (.-DrawerLayoutAndroid ReactNative)))
(def activity-indicator (r/adapt-react-class (.-ActivityIndicator ReactNative)))
(def refresh-control (r/adapt-react-class (.-RefreshControl ReactNative)))
(def ui-manager (.-UIManager ReactNative))
(def status-bar (r/adapt-react-class (.-StatusBar ReactNative)))
(def net-info (.-NetInfo ReactNative))
(def scroll-view (r/adapt-react-class (.-ScrollView ReactNative)))
